[project]
name = "accy575-wrds-data-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "matplotlib>=3.11.1",
    "numba>=0.61",
    "pandas>=2.2.3",
    "pandera>=0.32.1",
    "pyarrow>=25.0.0",
    "sentence-transformers>=5.7.0",
    "shap>=0.50.0",
    "statsmodels>=0.14.6",
    "torch>=2.13.0",
    "transformers>=5.14.1",
    "wrds>=3.5",
    "xgboost>=3.2.0",
]

[project.scripts]
accy575-wrds-data-analysis = "accy575_wrds_data_analysis:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.2",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
